import {StyleSheet, Dimensions} from 'react-native';

const deviceWidth = Dimensions.get('screen').width;

const styles = StyleSheet.create({
  title: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 25,
    textAlign: 'center',
    marginVertical: 10,
  },
  hourly_temp: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
    marginVertical: 5,
  },
  hourlyIconBackgroundStyle: {
    backgroundColor: 'rgba(108,66,67,0.5)',
    borderRadius: 150,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(65,39,40,0.5)',
  },
  containerBorderDailyTemp: {
    width: deviceWidth * 0.95,
    alignItems: 'center',
    height: 83,
    borderRadius: 15,
    justifyContent: 'center',
  },
  linearGradient: {
    width: deviceWidth * 0.94,
    height: 78,
    borderRadius: 15,
    justifyContent: 'space-around',
    flexDirection: 'row',
    paddingVertical: 10,
  },
  dailyWeatherText: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'serif',
    color: 'white',
    textAlign: 'center',
    alignSelf: 'center',
  },
  hourlyWeatherIcon: {
    alignSelf: 'center',
    marginVertical: 5,
  },
  detailText: {textAlign: 'center', fontWeight: 'bold'},
  cityName: {
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#e0e0e0',
    fontFamily: 'serif',
    alignSelf: 'center',
    marginHorizontal: 5,
    paddingHorizontal: 10,
  },
  detailCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    opacity: 0.7,
    height: 70,
    marginVertical: 10,
  },
  temperature: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 25,
  },
  detailIcon: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: 24,
    height: 24,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 15,
  },
  hourlyWeatherDetail: {
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#1e1e1e',
  },
  loading: {
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'serif',
    fontWeight: 'bold',
    fontSize: 50,
    color: '#e0e0e0',
  },
  locationSearchBar: {
    borderRadius: 20,
    borderWidth: 5,
    margin: 10,
    borderColor: '#e0e0e0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    top: 20,
  },
  containerBorderCityTemp: {
    width: deviceWidth * 0.45,
    margin: 10,
    alignItems: 'center',
    height: 120,
    borderRadius: 20,
    justifyContent: 'center',
  },
  containerCityTemp: {
    width: deviceWidth * 0.44,
    margin: 10,
    height: 115,
    borderRadius: 20,
    // justifyContent: 'center',
  },
  iconstyle: {
    fontSize: 30,
    alignSelf: 'center',
  },
  icontextstyle: {
    fontSize: 13,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  tabBarStyle: {
    position: 'absolute',
    bottom: 15,
    left: 20,
    right: 20,
    elevation: 15,
    borderRadius: 10,
    height: 60,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    shadowOpacity: 0.35,
    backgroundColor: 'rgba(238,238,238,0.6)',
  },
});

export default styles;
